/* #------------------ License ------------------#
*  #---------- Created By FastDevil -------------#
*  #--------- DO NOT EDIT this file -------------#
*  #------- This file is a library part ---------#
*  #---------------------------------------------#
*  #-------- ©Copyright FastDevil 2024 ----------#
*  #---------------------------------------------#
*/

#pragma warning disable

using FastDevil.Debug.CRT_Tasks;

namespace FastDevil.Debug;

sealed class CRT_Msg : CRT_MsgT{
    private readonly string? _message;
    private readonly byte _messageColor = 8;
    private readonly string _lbr = "\n";
    public void CE_Msg(){
        Console.ForegroundColor = (ConsoleColor)_messageColor;
        CE_Msg_Out(_message);
        CE_Lbr();
        Console.ForegroundColor = ConsoleColor.White;
    }
    private void CE_Msg_Out(string? _message){
        Console.Write($"Message: {_message}");
    }
    private void CE_Lbr(){
        Console.Write(_lbr);
    }
    public CRT_Msg(string? _message){
        this._message = _message;
        CE_Msg();
    }
}