/* #------------------ License ------------------#
*  #---------- Created By FastDevil -------------#
*  #--------- DO NOT EDIT this file -------------#
*  #------- This file is a library part ---------#
*  #---------------------------------------------#
*  #-------- ©Copyright FastDevil 2024 ----------#
*  #---------------------------------------------#
*/

namespace FastDevil.Debug{
    class App{
        public static void Exec_Config(){
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Console.Title = "My CRT test";
        }
        public static void WaitKeyPress(){
            Console.ForegroundColor = ConsoleColor.Black;
            Console.Write("Press any key to close: ");
            Console.ReadKey(true);
        }
    }
}