/* #------------------ License ------------------#
*  #---------- Created By FastDevil -------------#
*  #--------- DO NOT EDIT this file -------------#
*  #------- This file is a library part ---------#
*  #---------------------------------------------#
*  #-------- ©Copyright FastDevil 2024 ----------#
*  #---------------------------------------------#
*/

namespace FastDevil.Project{
    sealed class Debug{
        public static void DisplayWarn(object Warn){
            Output.TextColor(ConsoleColor.DarkYellow);
            Console.WriteLine($"[Warn]: {Warn}");
        }
        public static void DisplayError(object Error){
            Output.TextColor(ConsoleColor.Red);
            Console.WriteLine($"[Error]: {Error}");
        }
        public static void DisplayLog(object Info){
            Output.TextColor(ConsoleColor.Cyan);
            Console.WriteLine($"[Log]: {Info}");
        }
    }
}