/* #------------------ License ------------------#
*  #---------- Created By FastDevil -------------#
*  #--------- DO NOT EDIT this file -------------#
*  #------- This file is a library part ---------#
*  #---------------------------------------------#
*  #-------- ©Copyright FastDevil 2024 ----------#
*  #---------------------------------------------#
*/

namespace FastDevil.Project{
    sealed class Output{
        public static void GetKey(){
            TextColor(ConsoleColor.DarkGreen);
            Console.Write("Press any key to close: ");
            Console.ReadKey();
        }
        public static void TextColor(ConsoleColor Tcolor){
            Console.ForegroundColor = Tcolor;
        }
        public static void BGColor(ConsoleColor BGcolor){
            Console.BackgroundColor = BGcolor;
        }
        public static void Display(object Data){
            TextColor(ConsoleColor.White);
            Console.Write(Data);
        }
        public static void DisplayL(){
            Console.WriteLine();
        }
        public static void DisplayL(object Data){
            TextColor(ConsoleColor.White);
            Console.WriteLine(Data);
        }
    }
}