/* #------------------ License ------------------#
*  #---------- Created By FastDevil -------------#
*  #--------- DO NOT EDIT this file -------------#
*  #------- This file is a library part ---------#
*  #---------------------------------------------#
*  #-------- ©Copyright FastDevil 2024 ----------#
*  #---------------------------------------------#
*/

#pragma warning disable

namespace FastDevil.Project{
    class ObjectData{
        private readonly static object? ObjecType;
        public static unsafe object GetRAMaddr(object Addr){
            IntPtr ptr;
            TypedReference refr;
            refr = __makeref(Addr);
            ptr = *(IntPtr*)&refr;
            string RAMaddr = "0x" + ptr.ToString("X").ToLower();
            Console.WriteLine(RAMaddr);
            return ptr;
        }
        public static unsafe int? TypeOf(object Obj) {
            Console.WriteLine(Obj);
            return null;
        }
        public unsafe static object? ByteSize<Type>(Type Obj){
            Console.WriteLine(sizeof(Type));
            return sizeof(Type);
        }
    }
}